name = "CMBTN"
uuid = "304a4505-afd6-4d8a-a50b-cbeeb7ad18fc"
authors = ["Alan Emiliano Ramirez Ayala <75821310+Replase@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
